version: "3.5"
services:
  zap_server:
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    image: xbacons/zap-server
    container_name: zap_server
    ports:
      - 3333:3333
    networks:
      backend:
        aliases:
          - zap_server
networks:
  backend:
