version: "3.5"
services:
  zap_server:
    build:
      context: .
      target: zap_server
    working_dir: /home/send_zap/server node
    volumes:
      - ./:/home/send_zap/server node
    image: xbacons/zap-server
    container_name: zap_server
    tty: true
    ports:
      - 3333:3333
    networks:
      backend:
        aliases:
          - zap_server
networks:
  backend:
