version: '3'
services:
  zap-mediate:
    image: xbacons/zap-mediate:latest
    container_name: zap-mediate
    volumes:
      - zap-mediate:/home/zap-mediate/server
    ports:
      - "3333:8080"
    restart: always

  zap-auth:
    image: xbacons/zap-auth:latest
    container_name: zap-auth
    ports:
      - "80:80"
    restart: always