version: '3'
services:
  zap-mediate:
    image: xbacons/zap-mediate:latest
    container_name: zap-mediate
    volumes:
      - zap-mediate:/home/zap-mediate/server
    ports:
      - "3333:8080"
    restart: always

  zap-auth:
    image: xbacons/zap-auth:latest
    container_name: zap-auth
    ports:
      - "80:80"
    restart: always

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: 'zap.flextech.com.py'
      STAGE: local
      FORCE_RENEW: 'true'
      #STAGE: 'production' # Don't use production until staging works